### ISSUE TITLE
Add licenses for code, data, and models

### ISSUE THREAD

**Issue by scottveirs** [Salmon-Computer-Vision/salmon-computer-vision#56]
Thank you for sharing so much of your work via an open repository! It was refreshing to find the link within your publication [here](https://www.frontiersin.org/articles/10.3389/fmars.2023.1200408/full#h6) -- though please note that the URL in the article yields a 404 error upon selection because it includes the closed parenthesis (that I'm sure was meant to be plain text, not part of the hypertext link).

Based on our experiences with open audio data and models at [Orcasound](https://github.com/orcasound), I'd recommend adding licenses to the repository to clarify how you intend to share your work, including ideally each of:

1. A [LICENSE file in the repo](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) that covers the open source code you've shared
2. A [Creative Commons license](https://creativecommons.org/share-your-work/cclicenses/) for the image and label data sets
3. A [RAIL](https://www.licenses.ai/) for the model(s)

Careful what you fish for!

**Comment by KamiCreed** [comment]
Thanks for notifying us about this! I've added relevant licenses to the repo with quick links in the `README.md`.
